services:
  postgres:
    image: postgres:17
    command: postgres -c 'max_connections=1000'
    container_name: morefixes_db26
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data26:/var/lib/postgresql/data
      - ./dump-2026-06-20.sql.gz:/docker-entrypoint-initdb.d/dump-2026-06-20.sql.gz

volumes:
  postgres_data26:
